# Generated by Django 4.2.5 on 2023-09-28 18:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("monty_hall", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="gamerun",
            name="stick_losses",
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="gamerun",
            name="stick_wins",
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="gamerun",
            name="switch_losses",
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="gamerun",
            name="switch_wins",
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
